version: '3.1'
# TODO: per evitare che le porte siano hardcoded, possiamo usare il parametro env_file
#  env_file:
#    - my-env-file
# poi possiamo inserire nel file una variabile d'ambiente PORT e possiamo accedere alla porta in questo modo:
#  ports:
#    - ${PORT}:${PORT}
services:
  # I nostri containers
  frontend:
    image: "web_ui"
    container_name: "SDCCShoppingList"
    build: "src/frontend"
    ports:
      - "3000:3000"
  api_gateway:
    image: "api_gateway"
    container_name: "ApiGateway"
    build: "src/api_gateway"
    volumes:
      - "./config.properties:/api_gateway/config.properties"
      - "./src/proto:/api_gateway/proto"
    ports:
      - "8007:8007"
    depends_on:
      - shopping_list
#      - product_storage
#      - recipes
#      - consumptions
#      - notifications
#      - summary
  shopping_list:
    image: "shopping_list"
    container_name: "ShoppingListService" # attenzione potrebbe dare problemi se replichiamo
    build: "src/microservices/shopping_list"
    volumes:
      - "./config.properties:/usr/src/shopping_list/config.properties"
      - "./src/proto:/usr/src/shopping_list/proto"
    depends_on:
      - mongo
  product_storage:
    image: "product_storage"
    container_name: "ProductStorageService"
    build: "src/microservices/product_storage"
    volumes:
      - "./config.properties:/product_storage/config.properties"
      - "./src/proto:/product_storage/proto"
#  recipes:
#    image: recipes
#    container_name: "RecipesService"
#    build: "src/microservices/recipes"
#    volumes:
#      - "./config.properties:/usr/src/recipes"
#      - "./src/proto:/usr/src/recipes/proto"
#  consumptions:
#    image: consumptions
#    container_name: "ConsumptionService"
#    build: "src/microservices/consumptions"
#    volumes:
#      - "./config.properties:/usr/src/consumptions"
#      - "./src/proto:/usr/src/consumptions/proto"

  # notifications:
  #   image: notifications
  #   container_name: "NotificationsService"
  #   build: "src/microservices/notifications"
  #   volumes:
  #     - "src/microservices/notifications:/usr/src/notifications"
  #     - "./config.properties:/usr/src/notifications"
  # summary:
  #   image: summary
  #   container_name: "SummaryService"
  #   build: "src/microservices/summary"
  #   volumes:
  #     - "src/microservices/summary:/usr/src/summary"
  #     - "./config.properties:/usr/src/summary"
  
  # database mongodb. 
  # Todo: aggiungere questo database all'interno del microservizio product_storage
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # command: mongod

  # # UI per amministrare MongoDB
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-site
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
