FROM maven:3.8.2-eclipse-temurin-17
WORKDIR /summary
RUN mkdir -p src/main/proto
COPY microservices/summary/pom.xml ./pom.xml
RUN mvn dependency:go-offline
COPY proto ./src/main/proto
COPY microservices/summary/src ./src
RUN mvn verify
# RUN mvn dependency:go-offline
# CMD ["tail", "-f", "/dev/null"]
#CMD ["java", "-cp", "target/notifications-1.0-jar-with-dependencies.jar", "com.sdcc.shoppinglist.server.SummaryServer", "kafka://kafka:9092"]
EXPOSE 8006
CMD ["mvn", "exec:java", "-q", "-D\"exec.mainClass=com.sdcc.shoppinglist.server.SummaryServer\"", "-Dexec.args=\"kafka://kafka:9092\""]