# syntax=docker/dockerfile:1
FROM python:3.9

WORKDIR /usr/src/consumptions

COPY microservices/consumptions/requirements.txt requirements.txt
COPY proto ./proto
COPY microservices/consumptions .

RUN pip3 install -r requirements.txt
RUN python3 -m grpc_tools.protoc -I proto --python_out=. --pyi_out=. --grpc_python_out=. proto/*.proto

CMD python3 -u ./__main__.py