# syntax=docker/dockerfile:1
FROM python:3.9

WORKDIR /usr/src/consumptions

COPY microservices/consumptions/requirements.txt requirements.txt
COPY proto ./proto
COPY microservices/consumptions .

RUN apt-get update && apt-get install -y python3.9
RUN pip3 install -r requirements.txt
RUN python3 -m grpc_tools.protoc -I proto --python_out=generated --pyi_out=generated --grpc_python_out=generated proto/*.proto

CMD python3 ./__main__.py