# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import consumptions_pb2 as consumptions__pb2
import product_storage_pb2 as product__storage__pb2


class EstimatorStub(object):
    """service which can be executed
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/consumptions.Estimator/Predict',
                request_serializer=consumptions__pb2.PredictRequest.SerializeToString,
                response_deserializer=consumptions__pb2.PredictedDataList.FromString,
                )
        self.TrainModel = channel.unary_unary(
                '/consumptions.Estimator/TrainModel',
                request_serializer=product__storage__pb2.Item.SerializeToString,
                response_deserializer=consumptions__pb2.TrainResponse.FromString,
                )


class EstimatorServicer(object):
    """service which can be executed
    """

    def Predict(self, request, context):
        """This function should receive and return a stream of object
        rpc Predict(stream BoughtProduct) returns (stream BuyMore);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstimatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=consumptions__pb2.PredictRequest.FromString,
                    response_serializer=consumptions__pb2.PredictedDataList.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=product__storage__pb2.Item.FromString,
                    response_serializer=consumptions__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'consumptions.Estimator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Estimator(object):
    """service which can be executed
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/consumptions.Estimator/Predict',
            consumptions__pb2.PredictRequest.SerializeToString,
            consumptions__pb2.PredictedDataList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/consumptions.Estimator/TrainModel',
            product__storage__pb2.Item.SerializeToString,
            consumptions__pb2.TrainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
