# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\rnotifications\"\x15\n\x13NotificationRequest\"(\n\x10NotificationList\x12\x14\n\x0cnotification\x18\x01 \x03(\t2g\n\x0cNotification\x12W\n\x10GetNotifications\x12\".notifications.NotificationRequest\x1a\x1f.notifications.NotificationListB\x13Z\x11.;proto_generatedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021.;proto_generated'
  _NOTIFICATIONREQUEST._serialized_start=38
  _NOTIFICATIONREQUEST._serialized_end=59
  _NOTIFICATIONLIST._serialized_start=61
  _NOTIFICATIONLIST._serialized_end=101
  _NOTIFICATION._serialized_start=103
  _NOTIFICATION._serialized_end=206
# @@protoc_insertion_point(module_scope)
