# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notifications_pb2 as notifications__pb2


class NotificationStub(object):
    """service which can be executed
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNotifications = channel.unary_unary(
                '/notifications.Notification/GetNotifications',
                request_serializer=notifications__pb2.NotificationRequest.SerializeToString,
                response_deserializer=notifications__pb2.NotificationList.FromString,
                )


class NotificationServicer(object):
    """service which can be executed
    """

    def GetNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotifications,
                    request_deserializer=notifications__pb2.NotificationRequest.FromString,
                    response_serializer=notifications__pb2.NotificationList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notifications.Notification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Notification(object):
    """service which can be executed
    """

    @staticmethod
    def GetNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notifications.Notification/GetNotifications',
            notifications__pb2.NotificationRequest.SerializeToString,
            notifications__pb2.NotificationList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
