# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shopping_list_pb2 as shopping__list__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\rnotifications\x1a\x13shopping_list.proto2\x92\x01\n\x0cNotification\x12\x41\n\x0eNotifyDeadline\x12\x16.shopping_list.Product\x1a\x17.shopping_list.Response\x12?\n\x0cNotifyRunOut\x12\x16.shopping_list.Product\x1a\x17.shopping_list.ResponseB\x13Z\x11.;proto_generatedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021.;proto_generated'
  _NOTIFICATION._serialized_start=60
  _NOTIFICATION._serialized_end=206
# @@protoc_insertion_point(module_scope)
