# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_storage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shopping_list_pb2 as shopping__list__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15product_storage.proto\x12\x0fproduct_storage\x1a\x13shopping_list.proto\"\x18\n\x08ItemName\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\"\x8a\x02\n\x04Item\x12\x0e\n\x06itemId\x18\x01 \x01(\x03\x12\x10\n\x08itemName\x18\x02 \x01(\t\x12(\n\x04type\x18\x03 \x01(\x0e\x32\x1a.shopping_list.ProductType\x12!\n\x04unit\x18\x04 \x01(\x0e\x32\x13.shopping_list.Unit\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12,\n\nexpiration\x18\x06 \x01(\x0b\x32\x18.shopping_list.Timestamp\x12\x10\n\x08lastUsed\x18\x07 \x01(\x03\x12\x11\n\tuseNumber\x18\x08 \x01(\x05\x12\x17\n\x0ftotalUsedNumber\x18\t \x01(\x05\x12\x15\n\rtimesIsBought\x18\n \x01(\x05\"1\n\x06Pantry\x12\'\n\x08products\x18\x01 \x03(\x0b\x32\x15.product_storage.Item\"{\n\x08UsedItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12!\n\x04unit\x18\x03 \x01(\x0e\x32\x13.shopping_list.Unit\x12,\n\x08itemType\x18\x04 \x01(\x0e\x32\x1a.shopping_list.ProductType\"\x0f\n\rPantryMessage2\xce\x03\n\x0eProductStorage\x12P\n\x19\x41\x64\x64\x42oughtProductsToPantry\x12\x1a.shopping_list.ProductList\x1a\x17.shopping_list.Response\x12\x44\n\x12\x41\x64\x64ProductToPantry\x12\x15.product_storage.Item\x1a\x17.shopping_list.Response\x12K\n\x15\x44ropProductFromPantry\x12\x19.product_storage.ItemName\x1a\x17.shopping_list.Response\x12G\n\x15UpdateProductInPantry\x12\x15.product_storage.Item\x1a\x17.shopping_list.Response\x12H\n\x12UseProductInPantry\x12\x19.product_storage.UsedItem\x1a\x17.shopping_list.Response\x12\x44\n\tGetPantry\x12\x1e.product_storage.PantryMessage\x1a\x17.product_storage.PantryB\x13Z\x11.;proto_generatedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_storage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021.;proto_generated'
  _ITEMNAME._serialized_start=63
  _ITEMNAME._serialized_end=87
  _DATE._serialized_start=89
  _DATE._serialized_end=137
  _ITEM._serialized_start=140
  _ITEM._serialized_end=406
  _PANTRY._serialized_start=408
  _PANTRY._serialized_end=457
  _USEDITEM._serialized_start=459
  _USEDITEM._serialized_end=582
  _PANTRYMESSAGE._serialized_start=584
  _PANTRYMESSAGE._serialized_end=599
  _PRODUCTSTORAGE._serialized_start=602
  _PRODUCTSTORAGE._serialized_end=1064
# @@protoc_insertion_point(module_scope)
