# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summary.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsummary.proto\x12\x07summary\"\x10\n\x0eSummaryRequest\"\xa4\x01\n\x0bSummaryData\x12\"\n\treference\x18\x01 \x01(\x0e\x32\x0f.summary.Period\x12\x17\n\x0fmostUsedProduct\x18\x02 \x01(\t\x12\x19\n\x11mostBoughtProduct\x18\x03 \x01(\t\x12\x11\n\ttimesUsed\x18\x04 \x01(\x05\x12\x13\n\x0btimesBought\x18\x05 \x01(\x05\x12\x15\n\rnumberExpired\x18\x06 \x01(\x05*,\n\x06Period\x12\n\n\x06Weekly\x10\x00\x12\x0b\n\x07Monthly\x10\x01\x12\t\n\x05Total\x10\x02\x32\xc5\x01\n\x07Summary\x12<\n\x0bWeekSummary\x12\x17.summary.SummaryRequest\x1a\x14.summary.SummaryData\x12=\n\x0cMonthSummary\x12\x17.summary.SummaryRequest\x1a\x14.summary.SummaryData\x12=\n\x0cTotalSummary\x12\x17.summary.SummaryRequest\x1a\x14.summary.SummaryDataBH\n\x1d\x63om.sdcc.shoppinglist.summaryB\x0cSummaryProtoP\x01Z\x11.;proto_generated\xa2\x02\x03SUMb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summary_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.sdcc.shoppinglist.summaryB\014SummaryProtoP\001Z\021.;proto_generated\242\002\003SUM'
  _PERIOD._serialized_start=211
  _PERIOD._serialized_end=255
  _SUMMARYREQUEST._serialized_start=26
  _SUMMARYREQUEST._serialized_end=42
  _SUMMARYDATA._serialized_start=45
  _SUMMARYDATA._serialized_end=209
  _SUMMARY._serialized_start=258
  _SUMMARY._serialized_end=455
# @@protoc_insertion_point(module_scope)
