ec2: # group name
  hosts: #
    vm01:
      ansible_host: 3.239.235.249
    vm02:
      ansible_host: 3.237.170.255
    vm03:
      ansible_host: 35.169.124.112
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ../terraform/labsuser.pem

manager:
  hosts:
    vm01:

worker:
  hosts:
    vm02:
    vm03:
