ec2: # group name
  hosts: #
    vm01:
      ansible_host: 34.238.254.181
    vm02:
      ansible_host: 54.88.73.9
    vm03:
      ansible_host: 35.173.232.208
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ../terraform/labsuser.pem

manager:
  hosts:
    vm01:

worker:
  hosts:
    vm02:
    vm03:
